### ISSUE TITLE
final identifier prevent inherit from Connection and overwrite the predefined Cassandra version.

### ISSUE THREAD

**Issue by grigacs91** [MichaelRoosz/php-cassandra#4]
Hi,

I'm reaching out because we recently upgraded Cassandra, and unfortunately, we noticed that the `Connection` class now has a `final`  modifier. Previously, we were able to inherit it and override the Cassandra version in our own class, but this is no longer possible.

Is the use of `final` modifier in this class really necessary? Since I see some protected functions there, it's not entirely clear to me.

We could also imagine a solution where the Cassandra driver version could be set or configured, like using setter or remove final if it isn't necessary.

Here is our previous solution:

```
class CassandraConnectionV4 extends \Cassandra\Connection
{
     __construct(...params) {
         parent::_construct(...params);

          $this->version = 0x4;
          $this->versionIn = 0x84;
    }
}
```

We'd prefer not to modify anything inside the vendor directory, it generates lot of `warn` logs and not an optimal solution.

Thank you in advance for your help!

Kind Regards,
Gergely Der

**Comment by MichaelRoosz** [comment]
Hello Gergely,

thank you for reaching out. In v1.1.0 you may now set a pool of allowed protocol versions via the new `allowedProtocolVersions` property in `ConnectionOptions`, which is passed in the Connection's constructor.

For now I would keep the `final` for the Connection class, since it makes sure that nobody is depending on internal methods and properties. However, if you still have a need to extend this class, I will consider it.

Kind Regards,
Michael

**Comment by MichaelRoosz** [comment]
In case you want to connect to Scylladb: the next version (v1.2.0) will add "initialProtocolVersion" to support protocol V4 for it (since it does not implement automatic negotiation of protocol versions).

**Comment by grigacs91** [comment]
Hello Michael,


I'd like to give some context. We are currently migrating to PHP version 8.4, and we wanted to update the library to version 1.1.0, but unfortunately we couldn’t because of this issue. Currently we are also rewriting our Cassandra implementation to use CQL. However, we still have some old Thrift-based Cassandra solutions. So until we complete the full migration to CQL everywhere, we need to keep using this version (we can't update it), and during this transitional period this is the only workable solution we see.

**We receive this error message if the protocol version is not explicitly set to v4:**

`Cassandra connection failed with error php-cassandra only supports CQL binary protocol versions v3, v4 and v5. Please upgrade your Cassandra to 2.1 or later.Cassandra connection failed with error php-cassandra only supports CQL binary protocol versions v3, v4 and v5. Please upgrade your Cassandra to 2.1 or later.`

However, if we could get this working in version 1.2.0, we would greatly appreciate it. 

**If I understand right, you want to implement the solution in "initialProtocolVersion". It is perfect solution for us. Appreciate for it**


Best Regards,
Gergely Der

**Comment by MichaelRoosz** [comment]
Hello Gergely,

thank you for the context. May I ask which server version you are using?
v1.2.0 is now out, and uses V4 to connect by default, so this should fix the issue hopefully. You may also now configure `initialProtocolVersion` via `ConnectionOptions`, if needed.

Best regards,
Michael

**Comment by grigacs91** [comment]
Hello Michael,

Yes of course, we are using the 3.11 Cassandra server version, planning to upgrade when the code use the CQL solution everywhere. Lib upgraded form v0.8.1 -> v1.2.0

I tested the change, it works as we expected. You can close this issue.

Thanks for your solution.

Best regards,
Gergely
